package progressbar;
import java.awt.*;
import javax.swing.*;
import static javax.swing.JOptionPane.*;

/**
 *
 * @author 1337
 */
public class ProgressBar extends JPanel {    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        jButton1.setText("jButton1");

        jProgressBar1.setForeground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration                   

    static final int MY_MINIMUM = 0;
    static final int MY_MAXIMUM = 100;

    public ProgressBar() {
        jProgressBar1 = new JProgressBar();
        jProgressBar1.setMinimum(MY_MINIMUM);
        jProgressBar1.setMaximum(MY_MAXIMUM);
        jProgressBar1.setStringPainted(true);
        add(jProgressBar1);
    }

    public void updateBar(int newValue) {
        jProgressBar1.setValue(newValue);
    }

    public static void main(String args[]) {
        final ProgressBar it = new ProgressBar();
        JFrame frame = new JFrame("Contoh Progress Bar");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(it);
        frame.pack();
        frame.setSize(300, 100);
        frame.setLocation(750, 250);
        frame.setVisible(true);

        for (int i=MY_MINIMUM; i<=MY_MAXIMUM; i++) {
            final int percent = i;
            try {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        it.updateBar(percent);
                    }
                });
                
                if (i==100) {
                    showMessageDialog(null, "Loading selesai");
                    System.exit(0);
                }
                
                java.lang.Thread.sleep(100);
            } catch (InterruptedException e) {;
            }
        }
    }
}
